// @ts-nocheck
/**
 * This file is automatically generated by Firebase Studio.
 * Do not edit this file manually.
 */

import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  "projectId": "shift-flow-472313",
  "appId": "1:56625613200:web:73cf4ab8436934f86a0b15",
  "apiKey": "AIzaSyCVSiI9yLBOUi3Y2lX0klE0CREgRwqn8zY",
  "authDomain": "shift-flow-472313.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "56625613200"
};
